DROP TABLE if EXISTS stats;

CREATE TABLE stats (
                       statistic_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       uri varchar(1024) NOT NULL ,
                       app varchar(255) NOT NULL ,
                       ip varchar(255) NOT NULL ,
                       timestamp timestamp NOT NULL ,
                       PRIMARY KEY (statistic_id)
);