DROP TABLE if EXISTS users;

CREATE TABLE users (
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    email varchar NOT NULL UNIQUE ,
    name varchar NOT NULL ,
    is_active boolean NOT NULL DEFAULT false,
    PRIMARY KEY (user_id)
);