ALTER TABLE if EXISTS compilation_event DROP CONSTRAINT if EXISTS fk_compilation_event_event;
ALTER TABLE if EXISTS compilation_event DROP CONSTRAINT if EXISTS fk_compilation_event_compilation;

DROP TABLE if EXISTS compilations;
DROP TABLE if EXISTS compilation_event;

CREATE TABLE compilations(
    compilation_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    title varchar NOT NULL ,
    pinned boolean NOT NULL DEFAULT false ,
    PRIMARY KEY (compilation_id)
);

CREATE TABLE compilation_event(
  event_id bigint NOT NULL ,
  compilation_id bigint NOT NULL ,
  PRIMARY KEY (event_id, compilation_id)
);

ALTER TABLE if EXISTS compilation_event ADD CONSTRAINT fk_compilation_event_event
    FOREIGN KEY (event_id) REFERENCES events(event_id);

ALTER TABLE if EXISTS compilation_event ADD CONSTRAINT fk_compilation_event_compilation
    FOREIGN KEY (compilation_id) REFERENCES compilations(compilation_id);