ALTER TABLE if EXISTS requests DROP CONSTRAINT if EXISTS fk_request_event;
ALTER TABLE if EXISTS requests DROP CONSTRAINT if EXISTS fk_request_requester;

DROP TABLE if EXISTS requests;

CREATE TABLE requests (
    request_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    created timestamp NOT NULL ,
    status varchar NOT NULL ,
    event_id bigint NOT NULL ,
    requester bigint NOT NULL ,
    PRIMARY KEY (request_id)
);

ALTER TABLE if EXISTS requests ADD CONSTRAINT fk_request_event FOREIGN KEY (event_id)
    REFERENCES events(event_id);
ALTER TABLE if EXISTS requests ADD CONSTRAINT fk_request_requester FOREIGN KEY (requester)
    REFERENCES users(user_id);
