DROP TABLE if EXISTS stats;

CREATE TABLE stats (
    statistic_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uri varchar NOT NULL ,
    app varchar NOT NULL ,
    ip varchar NOT NULL ,
    timestamp timestamp NOT NULL ,
    PRIMARY KEY (statistic_id)
);